### ISSUE TITLE
page.url contains broken in latest master version

### ISSUE THREAD

**Issue by markvantilburg** [Code52/pretzel#228] opened 2015-03-23 12:57 UTC
This snippet does not work with the current version.
{% if page.url contains 'Oplossingen' %} active{% endif %}
The previous release build would put "active" when the file is this "Oplossingen-KlantMonitor.html" for example

**Comment by laedit** [comment] 2015-03-23 13:07
Thanks for the issue.
Just to be clear, with the current version the url have the same value and it's the use of `contains` in liquid which have some issue?
It can come from the last version of dotliquid, I will look.

**Comment by markvantilburg** [comment] 2015-03-23 13:11
The url is the same as before just the contains does not seem to be working.

**Comment by markvantilburg** [comment] 2015-03-23 13:14
Maybe it's my own build, i'll check the latest TC build

**Comment by laedit** [comment] 2015-03-23 13:15
Team City is not good right now, try with the [AppVeyor](https://ci.appveyor.com/project/laedit/pretzel/build/artifacts) build instead.

**Comment by markvantilburg** [comment] 2015-03-23 13:24
Checked with the AppVeyor build, page.Url is correct just the contains does not work

**Comment by laedit** [comment] 2015-03-23 13:41
The version of dotliquid used have not this issue, so pretzel must mess with the liquid.
The file having the problem is a layout or a content template?

**Comment by markvantilburg** [comment] 2015-03-23 13:56
_layouts/default.html 
which contains:

**Comment by markvantilburg** [comment] 2015-03-23 13:57
_layouts/default.html 
which contains:
{% include header-menu.html %}

And in the _includes/header-menu.html this code is used:
 {% if page.url contains 'Oplossingen' %} active{% endif %}

This to mark the current page link as 'active'

**Comment by laedit** [comment] 2015-03-23 18:53
`page.url` was no longer provided to the liquid engine so the if becomes `if '' contains 'Oplossingen'`.
It is now fixed, can you retry with the last version?
Thanks :smiley:

**Closed** 2015-03-23 18:52 UTC
Labels: Bug

**Comment by markvantilburg** [comment] 2015-03-23 20:08
I tried with the new appveyor build: Pretzel.0.2.1.121 and it's working good again +1
